target_folder: "Q:\\"
source_folder: "C:\\Users\\Niels\\My Drive"
compare_hashes: true 

use_veracrypt: true 
veracrypt_folder: "D:\\VeraCrypt"
veracrypt_command: veracrypt /volume \Device\Harddisk1\Partition2 /letter Q /p [password] /auto /quit

excluded_folders: 
    - .tmp.driveupload
    - .tmp.drivedownload